export const RASHI_INTERPRETATIONS: Record<string, string> = {
  Aries: 'Cardinal fire. The first spark of will — bold, pioneering, direct.',
  Taurus: 'Fixed earth. Steady, sensual, patient — an unshakeable grounding in the physical.',
  Gemini: 'Dual air. Quick, curious, communicative — a mind always in motion.',
  Cancer: 'Cardinal water. Nurturing, protective, deeply tied to home and mother.',
  Leo: 'Fixed fire. The royal lion — proud, generous, radiant in self-expression.',
  Virgo: 'Dual earth. Precise, analytical, healing — a mind that refines the world.',
  Libra: 'Cardinal air. Balancing, relational, aesthetic — the search for harmony.',
  Scorpio: 'Fixed water. Deep, transformative, intense — the alchemist of the zodiac.',
  Sagittarius: 'Dual fire. Seeking, philosophical, expansive — the archer aiming at truth.',
  Capricorn: 'Cardinal earth. Disciplined, ambitious, enduring — the mountain climber.',
  Aquarius: 'Fixed air. Visionary, humanitarian, unconventional — the water-bearer.',
  Pisces: 'Dual water. Compassionate, mystical, dissolving — the ocean of the soul.',
};

export const NAKSHATRA_INTERPRETATIONS: Record<string, string> = {
  Ashwini: 'The healer-riders. Swift beginnings, healing, pioneering energy.',
  Bharani: 'The bearer. Creativity, transformation, and the weight of care.',
  Krittika: 'The blade. Sharpness, courage, and purifying fire.',
  Rohini: 'The red one. Beauty, growth, and the fertile earth.',
  Mrigashira: 'The deer. Searching, gentle, ever-seeking sweetness.',
  Ardra: 'The moist one. Storms, tears, and raw emotion.',
  Punarvasu: 'Return of the light. Renewal, generosity, second chances.',
  Pushya: 'The nourisher. Deep care, spirituality, sacred support.',
  Ashlesha: 'The serpent. Coiled wisdom, healing, and hidden power.',
  Magha: 'The ancestors. Lineage, royalty, and inherited strength.',
  'Purva Phalguni': 'The front of the fig. Play, pleasure, and creative delight.',
  'Uttara Phalguni': 'The back of the fig. Nobility, partnership, service.',
  Hasta: 'The hand. Skill, craftsmanship, and healing touch.',
  Chitra: 'The bright jewel. Artistry, design, radiant presence.',
  Swati: 'The sword. Independence, diplomacy, and self-reliant grace.',
  Vishakha: 'The forked branch. Ambition, triumph, determined focus.',
  Anuradha: 'Following Radha. Devotion, friendship, deep loyalty.',
  Jyeshtha: 'The elder. Seniority, protection, hidden strength.',
  Mula: 'The root. Deep investigation, breaking free, spiritual roots.',
  'Purva Ashadha': 'The early victory. Invincible spirit, purifying ambition.',
  'Uttara Ashadha': 'The later victory. Universal victory, quiet strength.',
  Shravana: 'The ear. Listening, learning, sacred knowledge.',
  Dhanishta: 'The drum. Rhythm, prosperity, music of the cosmos.',
  Shatabhisha: 'The hundred healers. Healing, mystery, and vast vision.',
  'Purva Bhadrapada': 'The burning pair. Intense spirituality, fiery depths.',
  'Uttara Bhadrapada': 'The serpent of the deep. Wisdom, detachment, mystical insight.',
  Revati: 'The wealthiest. Nourishment, protection, gentle endings.',
};

/**
 * Narrative paragraph for each of the three anchors.
 * 2-3 sentences describing the essence.
 */
export const ANCHOR_NARRATIVES: Record<string, Record<string, string>> = {
  Lagna: {
    Aries: 'You arrive as fire — direct, courageous, a pioneer who moves first and thinks later. The body leads.',
    Taurus: 'You arrive as earth — steady, patient, grounded. The bull does not hurry, and does not yield.',
    Gemini: 'You arrive as air — curious, quick, communicative. The mind leads the body, always in motion.',
    Cancer: 'You arrive as water — nurturing, protective, deeply felt. The body remembers what the mind forgets.',
    Leo: 'You arrive as fire — regal, generous, radiant. The world is your stage, and you are here to shine.',
    Virgo: 'You arrive as earth — precise, analytical, healing. You refine the world through service.',
    Libra: 'You arrive as air — balancing, relational, aesthetic. You seek harmony in every exchange.',
    Scorpio: 'You arrive as water — deep, intense, transformative. You are here to die and be reborn.',
    Sagittarius: 'You arrive as fire — seeking, philosophical, expansive. The horizon is your home.',
    Capricorn: 'You arrive as earth — disciplined, ambitious, enduring. You climb the mountain that others fear.',
    Aquarius: 'You arrive as air — visionary, humanitarian, unconventional. You are here for the collective.',
    Pisces: 'You arrive as water — compassionate, mystical, dissolving. You remember you are not the body.',
  },
  Chandra: {
    Aries: 'Inside, a warrior. The mind is quick to anger and quick to move. Rest is a discipline you must learn.',
    Taurus: 'Inside, a garden. The mind is calm, steady, and deeply sensual. Emotions arrive slowly but stay.',
    Gemini: 'Inside, a library. The mind is always talking — to itself, to others, to the air. Silence is medicine.',
    Cancer: 'Inside, a mother. The mind feels everything deeply. Home is not a place but a feeling.',
    Leo: 'Inside, a king. The mind needs to be seen, admired, and respected. Your heart is both generous and proud.',
    Virgo: 'Inside, a healer. The mind is analytical, self-critical, and always improving. Perfection is a trap.',
    Libra: 'Inside, a mirror. The mind seeks balance, partnership, beauty. You feel most yourself with another.',
    Scorpio: 'Inside, an ocean. The mind is deep, private, transformative. You carry what others cannot.',
    Sagittarius: 'Inside, a wanderer. The mind seeks meaning, philosophy, distant horizons. Faith is your home.',
    Capricorn: 'Inside, an elder. The mind is serious, ambitious, and quietly powerful. You grew up early.',
    Aquarius: 'Inside, a visionary. The mind is different, futuristic, humanitarian. You are here to change things.',
    Pisces: 'Inside, a mystic. The mind dissolves into compassion and imagination. You feel the world\'s pain as your own.',
  },
  Surya: {
    Aries: 'At the core, a pioneer. The soul seeks bold, independent action.',
    Taurus: 'At the core, a builder. The soul seeks stability, beauty, and slow growth.',
    Gemini: 'At the core, a messenger. The soul seeks understanding, communication, connection.',
    Cancer: 'At the core, a caretaker. The soul seeks belonging, protection, and emotional truth.',
    Leo: 'At the core, a sovereign. The soul seeks creative self-expression and dignity.',
    Virgo: 'At the core, a craftsman. The soul seeks perfection, purity, and refined service.',
    Libra: 'At the core, a peacemaker. The soul seeks justice, beauty, and inner harmony.',
    Scorpio: 'At the core, an alchemist. The soul seeks truth at any cost, and rebirth through fire.',
    Sagittarius: 'At the core, a philosopher. The soul seeks meaning, dharma, and the highest knowledge.',
    Capricorn: 'At the core, a ruler. The soul seeks mastery, responsibility, and lasting achievement.',
    Aquarius: 'At the core, a reformer. The soul seeks freedom, equality, and the evolution of consciousness.',
    Pisces: 'At the core, a mystic. The soul seeks union, compassion, and dissolution into the divine.',
  },
};
